export const columns = [
    { field: "id", headerName: "Order ID", width: 90 },
    {
        field: "name",
        headerName: "Name",
        width: 150,
        editable: false,
    },
    {
        field: "address",
        headerName: "Address",
        width: 200,
        editable: false,
        resizable: true,
    },
    {
        field: "products",
        headerName: "Products",
        type: "list",
        width: 150,
        editable: false,
    },
    {
        field: "date",
        headerName: "Date",
        // description: 'This column has a value getter and is not sortable.',
        sortable: true,
        width: 200,
        // valueGetter: (params) =>
        //   `${params.row.firstName || ''} ${params.row.lastName || ''}`,
    },
    {
        field: "driver",
        headerName: "Driver",
        type: "string",
        width: 150,
        editable: false,
    },
];

export const rows = [
    {
        id: 11,
        name: "Snow",
        address: "Jon",
        products: 14,
        date: new Date().toLocaleString(),
        driver: "Kumaran",
    },
    {
        id: 2,
        name: "Lannister",
        address: "Cersei",
        products: 31,
        date: new Date().toLocaleString(),
        driver: "Kumaran",
    },
    {
        id: 43,
        name: "Lannister",
        address: "Jaime",
        products: 31,
        date: new Date().toLocaleString(),
        driver: "Kumaran",
    },
    {
        id: 4,
        name: "Stark",
        address: "Arya",
        products: 11,
        date: new Date().toLocaleString(),
        driver: "Kumaran",
    },
    {
        id: 5,
        name: "Targaryen",
        address: "Daenerys",
        products: null,
        date: new Date().toLocaleString(),
        driver: "Kumaran",
    },
    {
        id: 6,
        name: "Melisandre",
        address: null,
        products: 150,
        date: new Date().toLocaleString(),
        driver: "Kumaran",
    },
    {
        id: 237,
        name: "Clifford",
        address: "Ferrara",
        products: 44,
        date: new Date().toLocaleString(),
        driver: "Kumaran",
    },
    {
        id: 8,
        name: "Frances",
        address: "Rossini",
        products: 36,
        date: new Date().toLocaleString(),
        driver: "Kumaran",
    },
    {
        id: 9,
        name: "Roxie",
        address: "Harvey",
        products: 65,
        date: new Date().toLocaleString(),
        driver: "Kumaran",
    },
];